on: push

jobs:
  make-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4

      - name: Install dependencies
        run: npm install

      - name: Update docs
        run: npx jsdoc src -r -d docs

      - name: Commit changes
        run: git add docs && git commit -m "this is a docs update" && git push origin main
